E2E test validator
digitalservicebund/ris-norms pull request #395
Opened 2024-06-07 12:30 UTC by SebastianRossa

2024-06-07 14:31 UTC, andreasphil requested changes

2024-06-07 14:31 UTC, andreasphil commented on frontend/e2e/validation.spec.ts
> +test.describe("validation errors", () => {
Todo: this tests validation on a specific page, right? So it should be in that page's test file or at least be named more precisely

2024-06-07 14:31 UTC, andreasphil commented on frontend/e2e/validation.spec.ts
> +      "http://localhost:5173/amending-laws/eli/bund/bgbl-1/2017/s419/2017-03-15/1/deu/regelungstext-1/articles/hauptteil-1_art-1/edit/hauptteil-1_art-1_abs-1_untergl-1_listenelem-2_inhalt-1_text-1_%C
Todo: you can use a relative URL so we don't hardcode host and port. Same for the other URLs

2024-06-07 14:31 UTC, andreasphil commented on frontend/e2e/validation.spec.ts
> +    page.once("dialog", (dialog) => {
Question: I'm not sure what this is doing, but I assume this is going to be removed anyways once the result is reported with something other than alert boxes, right?

2024-06-12 13:07 UTC, andreasphil approved these changes

2024-06-19 09:41 UTC, closed without merging

2024-06-19 09:41 UTC, malte-laukoetter commented
merged in https://github.com/digitalservicebund/ris-norms/commit/6bca9f847137d1131c350a17b419b78a66121084