RISDEV-4434 create page for reference documentation no functionality
digitalservicebund/ris-norms pull request #489
Opened 2024-07-25 12:27 UTC by malte-laukoetter

2024-07-29 10:00 UTC, andreasphil requested changes

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/components/references/RisModSelectionPanel.vue
> +    <div v-if="normRenderLoading" class="flex justify-center">
Suggestion: I know replacing the UI with the spinner is our usual pattern but in this case it makes the UI feel a bit janky when showing a spinner for a split-second after every highlight or removing of a highlight. Some possible alternatives that come to mind:

- Debounce the spinner
- Show the spinner with a semi-transparent overlay on top of the UI instead of replacing it (possibly combined with debouncing)
- Show a small spinner inline next to the heading

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/components/references/RisModSelectionPanel.vue
> +  @apply block border border-[#4299F7] bg-[#E7E7E766] px-2;
Question: should we add these colors to our Tailwind config rather than hardcoding/arbitrary variants? Or do we know they won't be used anywhere else?

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/components/references/RisModSelectionPanel.vue
> +:deep(.akn-mod) {
Question: I'm not a huge fan of using `:deep`. I think it's fine for the preview component because of the `v-html`, but I would prefer if we didn't have this all across the app because it makes it harder to understand where styles come from, and harder to change the preview component as it also needs to work with all kinds of unpredictable styling overrides. Maybe we can find a different way to solve this?

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/components/references/RisModSelectionPanel.vue
> +:deep(.akn-mod) {
Side note: If we break out of the scoping anyways, maybe `style module` or simply `style` would be cleaner?

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/components/references/RisRefEditor.vue
> +    label="Löschen"
Question: do we need to generate a more dynamic/precise label here? I don't know how this will be logically grouped with the other inputs in this row but I'm not sure simply saying "Löschen" will be enough from the accessibility perspective to make the connection to what is being deleted.

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/services/xmlService.ts
> + * Convert the text representation of a xml document to a Document
Nitpick: I think `an` is actually correct here 😀

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/components/references/RisModSelectionPanel.vue
> +  normXml: string
Todo: docs

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/components/references/RisRefSelectionPanel.vue
> +:deep(.akn-quotedStructure .akn-quote-startQuote) {
Same here as above regarding the `deep` selectors

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/composables/useAknTextSelection.ts
> +export function useAknTextSelection(
todo: docs

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/lib/htmlRangeToLdmlDeRange.ts
> + * Finds the offset that is the corresponds to the same text range in the LDML.de node.
todo: IMO this could need some additional explanation about the algorithm that is used for finding the offset

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/lib/htmlRangeToLdmlDeRange.ts
> + * Converts a Range within a html-render of a LMDL.de xml to a range within that xml document.
todo: same here, some explanation about the algorithm would be appreciated

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/lib/ref.ts
> +  aknRef.setAttribute("GUID", uuidv4())
Question: is this a temporary GUID or will this also be the GUID in the backend? If it's the latter, it would feel better to me to have one actor in charge of generating IDs (in our case: the backend) to ensure data integrity and uniqueness (even though I admit that the likelihood of conflicts is low).

2024-07-29 10:00 UTC, andreasphil commented on frontend/src/views/References.vue
> +    triggerRef(amendingNormDocument)
I didn't know about `triggerRef`, nice! 💡

2024-07-29 10:11 UTC, malte-laukoetter commented on frontend/src/components/references/RisModSelectionPanel.vue
> +:deep(.akn-mod) {
The previous solution was to have all the different highlighting styles within the preview component itself (and properties to turn them on or off), but that became quite messy with the amount of different highlighting we want to have on different pages. 

The scoped style still (even with the deep) ensures that nothing outside of the component is affected by the style (but other than without the deep child components can be affected). So it still has advantages above a simple `style`. With `style module` I'm unsure how to achieve this kind of styling.

So yes it's not ideal but I couldn't find a better solution.

2024-07-29 10:14 UTC, malte-laukoetter commented on frontend/src/lib/ref.ts
> +  aknRef.setAttribute("GUID", uuidv4())
It's the final one. But as we are using UUIDs here (and especially v4 once) we do not have any data integrity or uniqueness problems as they are designed with the explicit purpose that lots of distributed actors can generate them and there will not be any conflicts. So it is totally fine to create the GUID on the frontend.

2024-07-29 14:15 UTC, malte-laukoetter commented on frontend/src/components/references/RisRefEditor.vue
> +    label="Löschen"
I'll look into this when I implement the other inputs of the component

2024-07-29 14:16 UTC, malte-laukoetter commented on frontend/src/services/xmlService.ts
> + * Convert the text representation of a xml document to a Document
atleast intellij complaint about "an" but I don't know 🤷

2024-07-29 14:22 UTC, malte-laukoetter commented on frontend/src/components/references/RisModSelectionPanel.vue
> +  @apply block border border-[#4299F7] bg-[#E7E7E766] px-2;
I think we should but they are currently different from the colors already defined for mods in other views so I don't know what to call them. Will talk to design about this ^^

2024-07-29 14:52 UTC, merged

2024-07-30 11:57 UTC, malte-laukoetter commented on frontend/src/components/references/RisRefEditor.vue
> +    label="Löschen"
I have grouped the inputs into sections which have the text content of the akn:refs as names